config/routes.rb
Rails.application.routes.draw do
	root to: "schooldetails#index"
	 resources :schooldetails
  
  # get 'schooldetails',to: 'schooldetails#index',as:'school_index'

  # get 'schooldetails/new',to: 'schooldetails#new'

  # get 'schooldetails/:id',to: 'schooldetails#show',as: 'school_find'

  # get 'schooldetails' ,to: 'schooldetails#create'

  # get 'schooldetails/edit/:id',to: 'schooldetails#edit',as: 'school_edit'

  # get 'schooldetails/:id',to: 'schooldetails#update',as: 'school_update'

  # get 'schooldetails/:id',to: 'schooldetails#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schooldetail.rb
class Schooldetail < ApplicationRecord
  validates :schoolname, presence: true, format: { with: /\A[a-zA-Z ]+\z/,
     message: "only allows letters" },length: {minimum: 5, maximum: 15}
     validates :address, presence: true,confirmation: { case_sensitive: false }
     validates :city, presence: true,length: {minimum: 5, maximum: 15}
     validates :state, presence: true,length: {minimum: 5, maximum: 15}
     validates :pincode, presence: true ,length: {minimum: 5, maximum: 10}
     validates :affiliatedboard, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/schooldetails_controller.rb
class SchooldetailsController < ApplicationController
   # before_action :set_schooldetail, only: [:show, :edit, :update, :destroy]
  def index
    @schooldetails = Schooldetail.all
  end

  def new
    @schooldetail = Schooldetail.new
  end

  def show
     @schooldetail = Schooldetail.find(params[:id])
  end

  def create
     @schooldetail = Schooldetail.new(schooldetail_params)
     p @schooldetail
     if @schooldetail.save
     p "success"
         render :json => @s

     else 
         # render json: @schooldetail.errors
       render :new
    end

  end

  def edit
    @schooldetail = Schooldetail.find(params[:id])
  end

  def update
      @schooldetail = Schooldetail.find(params[:id])
      if @schooldetail.update(schooldetail_params)
        p @schooldetail
        p "update"
         redirect_to @schooldetail
        else
          p "updateerror"
         render :edit 
      end
  end

  def destroy
    @schooldetail = Schooldetail.find(params[:id])
        @schooldetail.destroy
        redirect_to schooldetails_url
  end

  
  private
  def schooldetail_params
    params.require(:schooldetail).permit(:schoolname, :address,:city,:state,:pincode,:affiliatedboard)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schooldetails_helper.rb
module SchooldetailsHelper
end

app/views/layouts/application.html.erb
<!-- <!DOCTYPE html>
<html>
  <head>
    <title>Vzschoolform</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
    <div class="container-fluid">
      <div class="logo-part">
        <img class="logo" alt="Brand" src="../assets/Skala-icon.png"> 
       <%= link_to image_tag("settings.svg",class:'a') %>
        </div>
    </div>
  </header>
  <div class="navbar">
      <ul class="">
      <li><img alt="Brand" src="../assets/male3.svg"> <%= link_to 'User Management Portal', new_schooldetail_path %></li>
      <li><img alt="Brand" src="../assets/cash-register.svg"><%= link_to 'Registration Portal', new_schooldetail_path %></li>
      <li><img alt="Brand" src="../assets/controls.svg"> <%= link_to 'Content Portal', new_schooldetail_path %></li> 
    </ul>
  </div>
 
    <%= yield %>
  </body>
</html> -- -->
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
  <ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">one</a></li>
  <li><a href="#!">two</a></li>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
</ul>

<nav class="nav-extended">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
       <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><i class="material-icons right">settings</i></a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">JavaScript</a></li>
      </ul>

      <ul class="move tabs tabs-transparent">
        <li class="tab"><a href="#test1">User Management Portal</a></li>
        <li class="tab"><a class="active" href="#test2">Registration Portal</a></li>
        <li class="tab disabled"><a href="#test3">Content Portal</a></li>
       <!--  <li class="tab"><a href="#test4">Test 4</a></li> -->
      </ul>
    </div>
  </nav>
  
        

      
    <%= yield %>
  </body>
</html>





<!-- <!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/schooldetails/_form.html.erb
<%= form_for @schooldetail do |f| %>
<% if schooldetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schooldetail.errors.count, "error") %></h2>

      <ul>
      <% schooldetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class ="form">
<h1 id= "newschooldetails">NEW SCHOOl DETAILS </h1>
 <img  src="../assets/Cancel-128.png" class="deleteimg1"> 
<div class= "part1">
     <div class="row ">
        <div class="input-field col inline">
                 <%= f.text_field :schoolname,required: true, id:"schooldetail_schoolname",class:" school-create-validation",autofocaus: true,maxlength: 15 %>
               <label for="schoolname" id="schoolname" data-error="" data-success="right" class="error-first" >SCHOOLNAME</label>
        </div>
      </div>
      <div class="row s9">
        <div class="input-field col s9">
           <%= f.text_area :address ,required: true,class:"school-create-validation"%>
               <label for="address" id="schoola" data-error="" data-success="right" class="error-first">ADDRESS</label>  
        </div>
      </div>
      <div class="row s9">
        <div class="input-field col s9">
            <%= f.text_field :city,id:"schoolcity",class:"school-create-validation",required: true ,maxlength: 10 %>
               <label for="city" id="schoola" data-error="" data-success="right" class="error-first">CITY</label>  
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
            <%= f.text_field :state,id:"schoolstate",class:"school-create-validation",required: true ,maxlength: 10 %>
               <label for="state" id="schoola" data-error="wrong" data-success="right" class="error-first">STATE</label>  
        </div>
      </div>
       <div class="row">
        <div class="input-field col s12">
            <%= f.number_field :pincode ,id:"pincode",class:"school-create-validation",required: true,maxlength: 6%>
               <label for="pincode" id="schoola" data-error="wrong" data-success="right" class="error-first">PINCODE</label>  
        </div>
      </div>
</div>

      

  
<div class="left-part">

    <%= f.label :name ,"AFFILIATED BOARD:", class:"text-muted",id:"error-first" %><br/>
    <div class="field">
    <p>
      <%= f.radio_button :affiliatedboard, :value => 'CBSE', id:"test1"%>
      <label for="test1" value="CBSE">
      <span class="test1">CBSE</span></label>
    
    
     
      <%= f.radio_button :affiliatedboard, 'ICSE', id:"test2"%>
      <label for="test2" value="ICSE"><span class="test1">ICSE</span></label>
    
    
      <%= f.radio_button :affiliatedboard, 'Matric', id:"test3"%>
      <label for="test3" value="ICSE"><span class="test1">ICSE</span></label></br>
    </p></br>
    <p>
      <%= f.radio_button :affiliatedboard, 'State Board', id:"test4"%>
      <label for="test4" value="State Board"><span class="test1">State Board</span></label>
    </p>
  </div>
 
      <div class="section wizard">
<div class="submit custome-btn btn-floating btn-large waves-effect waves-light cyan darken-1 wizard" id= "width">
    <%= f.submit '>', class:"submit-button"%>
</div>
<div class = "ssub">
    <%= link_to '', new_schooldetail_path, class:"custome-btn btn-floating btn-large waves-effect waves-light wizard blue-grey darken-3",id:"sub" %>
    <%= link_to '', new_schooldetail_path, class:"custome-btn btn-floating btn-large waves-effect waves-light wizard blue-grey darken-3",id:"sub" %>
    <%= link_to '',new_schooldetail_path, class:"custome-btn btn-floating btn-large waves-effect waves-light wizard blue-grey darken-3", id:"sub" %>
</div>
     </div>
     </div>
     
 
<% end %>
<script type = "text/javascript">
var iChars = "!@#$%^&*()+=-_[]\\\';,./{}|\":<>?~`";
const numbers = "0123456789";
 
$(document).ready(function(){
  var label = document.getElementsByClassName('error-first');
 console.log( label)
 var input = document.getElementsByClassName('school-create-validation');
 console.log(input)
    for(var i=0; i<input.length; i++) {
     $(input[i]).bind("change focusout", function() {
        validation($(this),$(this).next())
    })
     // $(input[i]).focusout(function() {
    //         validation($(this), $(this).next())
    //     })
        // input[i].addEventListener('onFocus', validation(input[i], label[i]))
    }
function validation(inputValue,labelValues){
  console.log(inputValue);
  var input = inputValue.val();
  console.log(input)
  var labelValue = labelValues[0];
  console.log(labelValue)
   console.log($(inputValue).attr('id'))
   

   if(input.trim() === ''){
     console.log("e1")
    $(labelValue).attr('data-error',"can't be emity");
    return $(inputValue).addClass("invalid").removeClass("valid")

   }else{

   }
   if($(inputValue).attr('id') === "pincode"){
       if(input.length === 6){
      return $(inputValue).addClass("valid").removeClass("invalid")

     }else{
      return $(inputValue).addClass("invalid").removeClass("valid")

     }
}
else{
  for(var i= 0;i<input.length;i++){
    if(input[i] === ' ' && input[i + 1] === ' '){
      $(inputValue).addClass("invalid");
      return $(labelValue).attr('data-error','Double space not allowed')
       
    }
    
    if(iChars.indexOf(input[i]) != -1){
      // alert("e4");
    $(inputValue).addClass("invalid").removeClass("valid");
    return $(labelValue).attr('data-error','special cheractor not allowed')
    
    
  }
   if(numbers.indexOf(input[i]) != -1){
      // alert("e2")
    $(inputValue).addClass("invalid");
    return $(labelValue).attr('data-error','number not allowed')
       
       
    }
}

}

return $(inputValue).addClass("valid").removeClass("invalid")
}
});
</script>

app/views/schooldetails/edit.html.erb
	
<%= render 'form', schooldetail: @schooldetail %>

app/views/schooldetails/index.html.erb
<h1>SCHOOL DETAILS</h1>
<table class="bordered">
<thead>
<tr>
<th>Schoolname</th>
<th>Address</th>
<th>City</th>
<th>State</th>
<th>Pincode</th>
<th>Affiliatedboard</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @schooldetails.each  do |schooldetail| %>
  <tr>
  <td><%= schooldetail.schoolname %></td>
  <td><%= schooldetail.address %></td>
  <td><%= schooldetail.city %></td>
  <td><%= schooldetail.state %></td>
  <td><%= schooldetail.pincode %></td>
  <td><%= schooldetail.affiliatedboard %></td>
  <td><%= link_to 'Show' ,schooldetail %></td>
  <td><%= link_to 'Edit',edit_schooldetail_path(schooldetail) %></td>
  <td><%= link_to 'Destroy', schooldetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

 <% end %>
 </tbody>
 </table>
 <br>
 <div class = "addschool">
 <h3><%= link_to '+',new_schooldetail_path ,class:"btn-floating btn-large waves-effect waves-light red",id:"new"%>
 </h3>
 </div>

app/views/schooldetails/new.html.erb
<%= render 'form', schooldetail: @schooldetail %>

app/views/schooldetails/show.html.erb
<h1>show schoolddeatils</h1>
<p>
<strong>Schoolname:</strong>
<%= @schooldetail.schoolname %>
</p>
<p>
<strong>Address:</strong>
<%= @schooldetail.address %>
</p>
<p>
<strong>City:</strong>
<%= @schooldetail.city %>
</p>
<p>
<strong>State:</strong>
<%= @schooldetail.state %>
</p>

<p>
<strong>Pincode:</strong>
<%= @schooldetail.pincode %>
</p>
<p>
<strong>Affiliatedboard:</strong>
<%= @schooldetail.affiliatedboard %>
</p>
<%= link_to 'Edit', edit_schooldetail_path(@schooldetail) %> |
<%= link_to 'Back', schooldetails_path %>